# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
